apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-app
  labels:
    app: crashloop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-app
  template:
    metadata:
      labels:
        app: crashloop-app
    spec:
      containers:
      - name: app
        image: nginx:broken  # invalid image to trigger CrashLoop
        ports:
        - containerPort: 80
