apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - env:
        - name: FOO
          value: bar
        image: nginx
        name: my-container
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/config
          name: my-volume
      volumes:
      - configMap:
          name: my-config-map
        name: my-volume
