apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - env:
        - name: MISSING_VAR
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: invalidimage
        name: my-container
        ports:
        - containerPort: 8080
          protocol: TCP
