apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
    spec:
      containers:
      - env:
        - name: FOO
          value: bar
        image: my-image
        name: web-container
        ports:
        - containerPort: 8080
          protocol: TCP
