apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - env:
        - name: FOO
          value: bar
        image: example.com/my-image
        name: my-container
      ports:
      - containerPort: 8080
--- This YAML is functionally broken because the `image` field in the container spec
  references an invalid image name, which does not exist.
...
