global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kube-chaos-ai'
    static_configs:
      - targets: ['host.docker.internal:8001'] 

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093